---
- name: AI500 progress meter
  hosts: all
  connection: local
  order: sorted
  vars:

  gather_facts: false
  tasks:
    - name: Check the calendar
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'date_time'
      delegate_to: localhost
      run_once: true

    - name: Start scoring
      ansible.builtin.set_fact:
        score: 0

    - name: "### 0. When the Cluster Starts ###"
      ansible.builtin.include_tasks: check_objects.yml
      vars:
        check_kind: Deployment
        check_namespace: "{{ inventory_hostname }}-jukebox"
        check_loop_items:
          - ds-pipeline-dspa
          - ds-pipeline-dspa
          - ds-pipeline-metadata-envoy-dspa
          - ds-pipeline-metadata-grpc-dspa
          - ds-pipeline-persistenceagent-dspa
          - ds-pipeline-scheduledworkflow-dspa
          - ds-pipeline-workflow-controller-dspa
          - feast-ui-feast-feature-server
          - feature-store
          - mariadb-dspa
          - minio
          - "{{ inventory_hostname }}-registry-db"
      when: ansible_date_time.weekday == 'Monday'

    - name: "### 1. When the Music Starts ###"
      ansible.builtin.include_tasks: check_objects.yml
      vars:
        check_kind: StatefulSet
        check_namespace: "{{ inventory_hostname }}-jukebox"
        check_loop_items:
          - "{{ inventory_hostname }}-hitmusic-wb"


    - name: "### 2.1. In the Rhythm of Data ###"
      tags:
        - never
      ansible.builtin.include_tasks: check_objects.yml
      vars:
        check_api_version: argoproj.io/v1alpha1
        check_kind: Workflow
        check_namespace: "{{ inventory_hostname }}-jukebox"
        check_loop_items:
          - "{{ inventory_hostname }}-hitmusic-wb"
      when: ansible_date_time.weekday == 'Monday' or ansible_date_time.weekday == 'Tuesday'


    - name: '## 2.2. Check for InferenceService ##'
      ansible.builtin.include_tasks: check_objects.yml
      vars:
        check_api_version: serving.kserve.io/v1beta1
        check_kind: InferenceService
        check_namespace: "{{ inventory_hostname }}-{{ loop_env }}"
        check_loop_items:
          - "jukebox"
      loop:
          - "jukebox"
          - "test"
          - "prod"
      loop_control:
        loop_var: loop_env

    - name: "### 3.1 From Studio To Stage ###"
      ansible.builtin.include_tasks: check_objects.yml
      tags:
        - never
      vars:
        check_kind: StatefulSet
        check_namespace: "{{ inventory_hostname }}-jukebox"
        check_loop_items: 
          - "{{ inventory_hostname }}-mlops-toolings"


    - name: '## 3.2. Check for AppProjects ##'
      ansible.builtin.include_tasks: check_objects.yml
      vars:
        check_api_version: argoproj.io/v1alpha1
        check_kind: AppProject
        check_namespace: "{{ inventory_hostname }}-toolings"
        check_loop_items:
          - jukebox-prod-project
          - jukebox-test-project
          - mlops-toolings-project

    - name: '## 3.2. Check for AppProjects ##'
      ansible.builtin.include_tasks: check_objects.yml
      vars:
        check_api_version: argoproj.io/v1alpha1
        check_kind: AppProject
        check_namespace: "{{ inventory_hostname }}-toolings"
        check_loop_items:
          - jukebox-prod-project
          - jukebox-test-project
          - mlops-toolings-project
 
    - name: '## 3.3. Check for Model Registries ##'
      ansible.builtin.include_tasks: check_objects.yml
      vars:
        check_api_version: route.openshift.io/v1
        check_kind: Route
        check_namespace: "rhoai-model-registries"
        check_loop_items:
          - "{{ inventory_hostname }}-registry-https"
          - "{{ inventory_hostname }}-prod-registry-https"
 
     
    - name: '## 3.4. Check for Jukebox UI routes ##'
      ansible.builtin.include_tasks: check_objects.yml
      vars:
        check_api_version: route.openshift.io/v1
        check_kind: Route
        check_namespace: "{{ loop_env }}"
        check_loop_items:
          - "jukebox-ui"
      loop:
        - "{{ inventory_hostname }}-test"
        - "{{ inventory_hostname }}-prod"
      loop_control:
        loop_var: loop_env
      
    - name: '## 3.5. Check for Continuous Training Pipelines ##'
      ansible.builtin.include_tasks: check_objects.yml
      vars:
        check_api_version: tekton.dev/v1
        check_kind: Pipeline
        check_namespace: "{{ inventory_hostname }}-toolings"
        check_loop_items:
          - "ct-pipeline"
          - "ct-alert-pipeline"
          - "post-prod-deploy-pipeline"

    - name: '## 4.1. Check for Sound! Grafana and Monitoring##'
      ansible.builtin.include_tasks: check_objects.yml
      vars:
        check_api_version: grafana.integreatly.org/v1beta1
        check_kind: Grafana
        check_namespace: "{{ inventory_hostname }}-toolings"
        check_loop_items:
          - "jukebox-grafana"

    - name: '## 4.1. Check for Sound! Grafana and Monitoring##'
      ansible.builtin.include_tasks: check_objects.yml
      vars:
        check_api_version: grafana.integreatly.org/v1beta1
        check_kind: GrafanaDashboard
        check_namespace: "{{ inventory_hostname }}-toolings"
        check_loop_items:
          - "grafana-trusty-dashboard"

    - name: '## 4.2. Check for ALARMS! Prometheus Alerting ##' 
      ansible.builtin.include_tasks: check_objects.yml
      vars:
        check_api_version: monitoring.coreos.com/v1
        check_kind: PrometheusRule
        check_namespace: "{{ loop_env }}"
        check_loop_items:
          - "jukebox-alerts"
      loop:
        - "{{ inventory_hostname }}-test"
        - "{{ inventory_hostname }}-prod"
      loop_control:
        loop_var: loop_env

    - name: '## 4.3. Check for Prometheus Alert Manager Configuration ##' 
      ansible.builtin.include_tasks: check_objects.yml
      vars:
        check_api_version: monitoring.coreos.com/v1beta1
        check_kind: AlertmanagerConfig
        check_namespace: "{{ loop_env }}"
        check_loop_items:
          - "jukebox-alerting"
      loop:
        - "{{ inventory_hostname }}-test"
        - "{{ inventory_hostname }}-prod"
      loop_control:
        loop_var: loop_env

    - name: '## Check and score how many predictors have been deployed ##'
      ansible.builtin.include_tasks: check_objects.yml
      vars:
        check_kind: Deployment
        check_namespace: "{{ loop_env }}"
        check_loop_items:
          - "jukebox-predictor-00001-deployment"
          - "jukebox-predictor-00002-deployment"
          - "jukebox-predictor-00003-deployment"
      loop:
        - "{{ inventory_hostname }}-test"
        - "{{ inventory_hostname }}-prod"
      loop_control:
        loop_var: loop_env


- name: Show the survivor scores
  hosts: all
  gather_facts: no
  tasks:
    - name: "Calculating..."
      ansible.builtin.debug: msg="{{ inventory_hostname }} has {{ score }} points"
