---
- name: AI500 progress meter
  hosts: all
  connection: local
  vars:
    pre_check_day: 'Monday'

  gather_facts: false
  tasks:
    - name: Check the calendar
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'date_time'
      delegate_to: localhost
      run_once: true


    - name: "### 0. When the Cluster Starts (only check on {{ pre_check_day }}) ###"
      ansible.builtin.include_tasks: check_objects.yml
      vars:
        check_kind: Deployment
        check_namespace: "{{ inventory_hostname }}-jukebox"
        check_loop_items:
          - ds-pipeline-dspa
          - ds-pipeline-dspa
          - ds-pipeline-metadata-envoy-dspa
          - ds-pipeline-metadata-grpc-dspa
          - ds-pipeline-persistenceagent-dspa
          - ds-pipeline-scheduledworkflow-dspa
          - ds-pipeline-workflow-controller-dspa
          - feast-ui-feast-feature-server
          - feature-store
          - mariadb-dspa
          - minio
          - "{{ inventory_hostname }}-registry-db"
      when: ansible_date_time.weekday == pre_check_day

    - name: "### 1. When the Music Starts ###"
      ansible.builtin.include_tasks: check_objects.yml
      vars:
        check_kind: StatefulSet
        check_namespace: "{{ inventory_hostname }}-jukebox"
        check_loop_items:
          - "{{ inventory_hostname }}-hitmusic-wb"


    - name: "### 2.1. In the Rhythm of Data ###"
      tags:
        - never
      ansible.builtin.include_tasks: check_objects.yml
      vars:
        check_api_version: argoproj.io/v1alpha1
        check_kind: Workflow
        check_namespace: "{{ inventory_hostname }}-jukebox"
        check_loop_items:
          - "{{ inventory_hostname }}-hitmusic-wb"


    - name: '## 2.2. Check for InferenceService ##'
      ansible.builtin.include_tasks: check_objects.yml
      vars:
        check_api_version: serving.kserve.io/v1beta1
        check_kind: InferenceService
        check_namespace: "{{ inventory_hostname }}-{{ loop_env }}"
        check_loop_items:
          - "jukebox"
      loop:
          - "jukebox"
          - "test"
          - "prod"
      loop_control:
        loop_var: loop_env

    - name: "### 3.1 From Studio To Stage ###"
      ansible.builtin.include_tasks: check_objects.yml
      vars:
        check_kind: StatefulSet
        check_namespace: "{{ inventory_hostname }}-jukebox"
        check_loop_items: 
          - "{{ inventory_hostname }}-mlops-toolings"


    - name: '## 3.2. Check for AppProjects ##'
      ansible.builtin.include_tasks: check_objects.yml
      vars:
        check_api_version: argoproj.io/v1alpha1
        check_kind: AppProject
        check_namespace: "{{ inventory_hostname }}-toolings"
        check_loop_items:
          - jukebox-prod-project
          - jukebox-test-project
          - mlops-toolings-project
